### ISSUE TITLE
@OperationsPerInvocation这个参数的具体意义？

### ISSUE THREAD

**Issue by haidfs** [ihaolin/java-benchmark#2]
你好，能否请教一下@OperationsPerInvocation这个参数和jmh score之间的关系？比如在一个测试代码体中，有100000次循环，@OperationsPerInvocation(100000)得出的score为23369201.335 ops/s，将这个参数修改成@OperationsPerInvocation(1)（代码体循环次数不变），得出的score为246.563 ops/s，这两个有很明显的倍数关系。但是这两个评分该怎么理解？@OperationsPerInvocation(1)所给出的是单次循环的性能，@OperationsPerInvocation(100000)是所有循环的性能？很疑惑，求指教。

**Comment by ihaolin** [comment]
从这个注解的Comment来看，是这样的，
OperationsPerInvocation(1)表示一次调用包含1次操作，OperationsPerInvocation(100000)表示一次调用包含100000次操作，`ops/s`表示每秒的可执行的操作数。

**Comment by haidfs** [comment]
嗯...怎么说呢，从官网的文档[http://javadox.com/org.openjdk.jmh/jmh-core/0.9/org/openjdk/jmh/annotations/OperationsPerInvocation.html](url)和前辈你的说明来看，OperationsPerInvocation这里的operation应该是内存for循环的代码体。我理解的是，声明OperationsPerInvocation(1)的话，即使内层的for循环有100000次，实际Benchmark应该是只执行了一次的。但是我的疑问点是在于，不管我是执行1次还是100000次（放大），不应该会有这么大的性能差异（23369201.335 ops/s和246.563 ops/s），而且这两个跑分很明显有一个近似100000倍的关系。这两个跑分和OperationsPerInvocation的关系，应该怎么理解呢？

**Comment by ihaolin** [comment]
我的理解是，OperationsPerInvocation这个属性值是开发人员自己评估的，评估一次调用里会执行多少次操作，框架会帮你对应计算ops，比如开发人员认为for循环整体是一次操作，就设置为1，认为for循环内部是一次操作，就把OperationsPerInvocation设置为for的迭代次数，所以ops就对应放大了
